---
- name: Provision for 01Rouen laptops
  hosts: localhost
  become: true
  vars_files:
    - ./vars.yml

  # APT Packages
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install packages
      ansible.builtin.apt:
        name:
          - wget
          - curl
          - git
          - build-essential
          - network-manager
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
      when: ansible_os_family == "Debian"

    # Golang
    - name: Check if golang is installed
      ansible.builtin.stat:
        path: /usr/local/go/bin/go
      register: golang_installed

    - name: Get latest golang version
      ansible.builtin.uri:
        url: https://go.dev/VERSION?m=text
        return_content: true
        validate_certs: true
      register: golang_version_resp
      changed_when: false
      when: not golang_installed.stat.exists

    - name: Set latets golang version
      ansible.builtin.set_fact:
        golang_latest_version: "{{ golang_version_resp.content.split('\n')[0] }}"
      when: not golang_installed.stat.exists

    - name: Download latest golang version
      ansible.builtin.get_url:
        url: "https://go.dev/dl/{{ golang_latest_version }}.linux-amd64.tar.gz"
        dest: "/tmp/{{ golang_latest_version }}.linux-amd64.tar.gz"
        mode: "0644"
      when: not golang_installed.stat.exists

    - name: Remove old golang installation
      ansible.builtin.file:
        path: /usr/local/go
        state: absent
      when: not golang_installed.stat.exists

    - name: Extract golang archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ golang_latest_version }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: true
      when: not golang_installed.stat.exists

    - name: Add golang to path in /etc/profile.d
      ansible.builtin.copy:
        content: |
          export PATH=$PATH:/usr/local/go/bin
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
        dest: /etc/profile.d/golang.sh
        mode: "0644"

    - name: Add golang to path for student
      ansible.builtin.lineinfile:
        path: "/home/{{ student_user }}/.bashrc"
        mode: "0644"
        line: "{{ item }}"
        create: true
        owner: "{{ student_user }}"
        group: "{{ student_user }}"
      loop:
        - "export PATH=$PATH:/usr/local/go/bin"
        - "export GOPATH=$HOME/go"
        - "export PATH=$PATH:$GOPATH/bin"

    # VSCODE
    - name: Download Microsoft GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
        mode: "0644"
      when: ansible_os_family == "Debian"

    - name: Add Microsoft GPG key to keyring
      ansible.builtin.shell: |
        gpg --dearmor < /tmp/microsoft.asc > /usr/share/keyrings/packages.microsoft.gpg
        chmod 644 /usr/share/keyrings/packages.microsoft.gpg
      args:
        creates: /usr/share/keyrings/packages.microsoft.gpg
      when: ansible_os_family == "Debian"

    - name: Add VSCode repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode
      when: ansible_os_family == "Debian"

    - name: Install VSCode
      ansible.builtin.apt:
        name: code
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install VSCode extensions for student
      become: true
      become_user: "{{ student_user }}"
      ansible.builtin.command: "code --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
      register: vscode_ext_result
      changed_when: "'already installed' not in (vscode_ext_result.stdout | default(''))"
      failed_when: false

    # (Evil) Chrome
    - name: Download Google Chrome
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
        mode: "0644"

    - name: Install Google Chrome
      ansible.builtin.apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
      when: ansible_os_family == "Debian"

    # Browsers customization:: Chrome
    - name: Check if Chrome managed policy exists
      ansible.builtin.file:
        path: /etc/opt/chrome/policies/managed
        state: directory
        mode: "0755"

    - name: Force install uBlock + start packages
      ansible.builtin.copy:
        dest: /etc/opt/chrome/policies/managed/zone01.json
        mode: "0644"
        content: |
          {
            "ExtensionSettings": {
              "*": { "installation_mode": "allowed" },
              "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
                "installation_mode": "force_installed",
                "update_url": "https://clients2.google.com/service/update2/crx"
              }
            },
            "HomepageLocation": "file:///usr/local/share/browser-start/browser.html",
            "HomepageIsNewTabPage": false,
            "NewTabPageLocation": "file:///usr/local/share/browser-start/browser.html"
          }

    # Browsers customization:: Firefox
    - name: Check Firefox distribution dir exists
      ansible.builtin.file:
        path: /usr/lib/firefox/distribution
        state: directory
        mode: "0755"

    - name: Force-install uBlock + start page
      ansible.builtin.copy:
        dest: /usr/lib/firefox/distribution/policies.json
        mode: "0644"
        content: |
          {
            "policies": {
              "ExtensionSettings": {
                "uBlock0@raymondhill.net": {
                  "installation_mode": "force_installed",
                  "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
                }
              },
              "Homepage": {
                "URL": "file:///usr/local/share/browser-start/browser.html",
                "StartPage": "homepage",
                "Additional": [ "file:///usr/local/share/browser-start/browser.html" ]
              },
              "NewTabPage": {
                "URL": "file:///usr/local/share/browser-start/browser.html"
              }
            }
          }

    # Browsers customization:: Both
    - name: Ensure browser start directory exists
      ansible.builtin.file:
        path: /usr/local/share/browser-start
        state: directory
        mode: "0755"

    - name: Deploy custom start page
      ansible.builtin.copy:
        src: assets/browser.html
        dest: /usr/local/share/browser-start/browser.html
        mode: "0644"


    # Discord
    - name: Download Discord
      ansible.builtin.get_url:
        url: https://discord.com/api/download?platform=linux&format=deb
        dest: /tmp/discord.deb
        mode: "0644"
        force: true
      register: discord_download
      when: ansible_os_family == "Debian"

    - name: Install Discord
      ansible.builtin.apt:
        deb: /tmp/discord.deb
        state: present
      when: ansible_os_family == "Debian"

    # Install Node via nvm
    - name: Ensure nvm temp dir exists
      ansible.builtin.file:
        path: /tmp/nvm
        state: directory
        mode: "0755"

    - name: Download nvm script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh
        dest: /tmp/nvm/install.sh
        mode: "0644"

    - name: Install nvm
      become: true
      become_user: "{{ student_user }}"
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        mkdir -p "$NVM_DIR"
        bash /tmp/nvm/install.sh
      args:
        creates: "/home/{{ student_user }}/.nvm/nvm.sh"

    - name: Ensure nvm is loaded in bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ student_user }}/.bashrc"
        line: 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
        insertafter: EOF
        owner: "{{ student_user }}"
        group: "{{ student_user }}"
        mode: "0644"

    - name: Install Node LTS via nvm
      become: true
      become_user: "{{ student_user }}"
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm alias default 'lts/*'
      args:
        creates: "/home/{{ student_user }}/.nvm/alias"

    # @conotion/cli
    - name: Install @conotion/cli globally
      become: true
      become_user: "{{ student_user }}"
      ansible.builtin.shell: |
        set -euo pipefail
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        npm install -g @conotion/cli
      args:
        executable: /bin/bash
      changed_when: true

    # Wifi Configuration
    - name: Detect wifi interfaces
      ansible.builtin.shell: |
        set -o pipefail
        nmcli -t -f DEVICE,TYPE device status \
        | awk -F: '$2 == "wifi" { print $1 }'
      register: wifi_interfaces
      changed_when: false

    - name: Fail if no wifi interface is found
      ansible.builtin.fail:
        msg: "Aucune interface Wi-Fi détectée via nmcli"
      when: wifi_interfaces.stdout_lines | length == 0

    - name: Select wifi interface
      ansible.builtin.set_fact:
        wifi_interface: "{{ wifi_interfaces.stdout_lines[0] }}"

    - name: Get list of existing wifi connections
      ansible.builtin.shell: |
        set -o pipefail
        nmcli -t -f NAME,TYPE con show \
        | awk -F: '$2 == "802-11-wireless" { print $1 }'
      register: existing_wifi_connections
      changed_when: false
      failed_when: false

    - name: Remove existing wifi connections
      ansible.builtin.shell: |
        nmcli con delete '{{ item }}'
      loop: "{{ existing_wifi_connections.stdout_lines }}"
      register: wifi_delete
      when: existing_wifi_connections.stdout_lines | length > 0
      changed_when: wifi_delete.rc == 0
      failed_when: false

    - name: Configure wifi on campus
      ansible.builtin.shell: |
        nmcli con add type wifi ifname "{{ wifi_interface }}" con-name "{{ wifi_ssid }}" ssid "{{ wifi_ssid }}" || true
        nmcli con modify "{{ wifi_ssid }}" wifi-sec.key-mgmt wpa-psk wifi-sec.psk "{{ wifi_password }}"
        nmcli con up "{{ wifi_ssid }}" || true
      register: wifi_config
      changed_when: "'successfully activated' in wifi_config.stdout"
      failed_when: false

    # Plymouth
    - name: Ensure Plymouth themes are present
      ansible.builtin.apt:
        name: plymouth-themes
        state: present
      when: ansible_os_family == "Debian"

    - name: Find ubuntu-logo PNGs in theme dir
      ansible.builtin.find:
        paths: /usr/share/plymouth
        patterns: "ubuntu-logo*.png"
        recurse: true
        file_type: file
      register: plymouth_logo_files
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Replace Plymouth ubuntu-logo PNGs with custom logo
      ansible.builtin.copy:
        src: assets/01logo.png
        dest: "{{ item.path }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ plymouth_logo_files.files }}"
      when:
        - ansible_os_family == "Debian"
        - plymouth_logo_files.matched | int > 0
      notify: Rebuild initramfs

    - name: Get current Plymouth theme
      ansible.builtin.command: plymouth-set-default-theme
      register: plymouth_current
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Set Plymouth theme to ubuntu-logo (if needed)
      ansible.builtin.command: plymouth-set-default-theme ubuntu-logo
      register: plymouth_set
      changed_when: true
      when:
        - ansible_os_family == "Debian"
        - (plymouth_current.stdout | trim) != "ubuntu-logo"
      notify: Rebuild initramfs

    # Completed
    - name: Display completion message
      ansible.builtin.debug:
        msg: " Provisioning complete! "

  handlers:
    - name: Rebuild initramfs
      ansible.builtin.command: update-initramfs -u
      changed_when: true
      when: ansible_os_family == "Debian"
