---
- name: Reset user student
  hosts: localhost
  become: yes
  vars:
    student_user: "student"
    student_home: "/home/{{ student_user }}"
    repo_dir: "/opt/ansible01Prov"
    repo_url: "https://github.com/SpauriRosso/ansible01Prov.git"

  tasks:
    - name: Ensure provisioning repo is up to date
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: HEAD
        update: true
        force: true

    - name: Display warning about user reset
      debug:
        msg: "WARNING: This will completely remove and recreate the '{{ student_user }}' user, including all data!"

    - name: Remove student user home directory
      file:
        path: "{{ student_home }}"
        state: absent

    - name: Remove student mail spool
      file:
        path: "/var/mail/{{ student_user }}"
        state: absent

    - name: Remove student spool mail directory
      file:
        path: "/var/spool/mail/{{ student_user }}"
        state: absent

    - name: Force remove student user (even if logged in)
      ansible.builtin.command: "userdel -r -f {{ student_user }}"
      changed_when: true
      failed_when: false

    - name: Ensure student user is absent
      user:
        name: "{{ student_user }}"
        state: absent
        remove: yes
        force: yes

    - name: Create fresh student user
      user:
        name: "{{ student_user }}"
        state: present
        shell: /bin/bash
        createhome: yes
        home: "{{ student_home }}"

    - name: Set password for student
      user:
        name: "{{ student_user }}"
        password: "{{ 'Zone01pc' | password_hash('sha512') }}"
        update_password: always

    - name: Create standard directories for student
      file:
        path: "{{ student_home }}/{{ item }}"
        state: directory
        owner: "{{ student_user }}"
        group: "{{ student_user }}"
        mode: '0755'
      loop:
        - Desktop
        - Documents
        - Downloads
        - Pictures

    - name: Display reset completion message
      debug:
        msg: "User '{{ student_user }}' has been reset successfully."

# Import the provisioning playbook
- import_playbook: 01Prov.yml
